"""
G1 MPC RL 相关配置与默认路径
"""

from .g1_mpc_rl import (
    RESIDUAL_WEIGHT_DIM,
    DEFAULT_TASK_FILE,
    DEFAULT_URDF_FILE,
    DEFAULT_REF_FILE,
    DEFAULT_XML_FILE,
    DEFAULT_GAIT_FILE,
    DEFAULT_RL_FREQUENCY_HZ,
    DEFAULT_MPC_FREQUENCY_HZ,
    DEFAULT_SIM_FREQUENCY_HZ,
    get_g1_config,
)

__all__ = [
    "RESIDUAL_WEIGHT_DIM",
    "DEFAULT_TASK_FILE",
    "DEFAULT_URDF_FILE",
    "DEFAULT_REF_FILE",
    "DEFAULT_XML_FILE",
    "DEFAULT_GAIT_FILE",
    "DEFAULT_RL_FREQUENCY_HZ",
    "DEFAULT_MPC_FREQUENCY_HZ",
    "DEFAULT_SIM_FREQUENCY_HZ",
    "get_g1_config",
]
